- hosts: master
  become: yes
  #gather_facts: false
  tasks:
    - name: Retrieve Kubernetes join command that is used to join worker node(s)
      become: false
      when: inventory_hostname in groups['master']
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Attach kubeadm join command to a file on Ansible control node
      when: inventory_hostname in groups['master']
      local_action: "copy content='{{ join_command.stdout_lines[0] }}' dest=join-command"


- hosts: workers
  become: yes
  tasks:
    - name: install Kubectl
      apt:
        name: kubectl=1.26.*
        state: present
        force: yes
    - name: Copy the join-command file created above to worker node
      when: inventory_hostname in groups['workers']
      copy: src=join-command dest=/tmp/kubeadm-join.sh mode=0777

    - name: Join the worker node to cluster
      when: inventory_hostname in groups['workers']
      command: sh /tmp/kubeadm-join.sh
